# Generated by Django 4.2.1 on 2023-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=70)),
                ('task_description', models.CharField(max_length=300)),
                ('task_deadline', models.DateTimeField(verbose_name='deadline')),
            ],
        ),
        migrations.CreateModel(
            name='TimeKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_time', models.DateTimeField(verbose_name='to note the time')),
                ('spent_time', models.DurationField(verbose_name='spent time')),
            ],
        ),
    ]
