# Generated by Django 4.2.1 on 2023-06-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='timekeeper',
            options={'verbose_name_plural': 'Timekeeper'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
        migrations.AddField(
            model_name='task',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deadline'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='timekeeper',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='timekeeper',
            name='note_time',
            field=models.DateTimeField(blank=True, verbose_name='to note the time'),
        ),
        migrations.AlterField(
            model_name='timekeeper',
            name='spent_time',
            field=models.DurationField(blank=True, verbose_name='spent time'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskcategory'),
        ),
    ]
