# Generated by Django 4.2.1 on 2023-07-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeper',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='timekeeper',
            name='start',
            field=models.DateTimeField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='timekeeper',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timekeepers', to='tasks.task'),
        ),
    ]
