# Generated by Django 4.2.1 on 2023-06-16 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskcategory_alter_timekeeper_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Вы не указали задачу')]),
        ),
    ]
