# Generated by Django 4.2.1 on 2023-06-23 09:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.taskcategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='От 5 символов')]),
        ),
    ]
